config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :groups, only: [:new, :edit, :create, :update] do
    resources :messages, only: [:index, :create]
  end
  resources :users, only: :index do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :messages
  has_many :users, through: :group_users
  accepts_nested_attributes_for :group_users
  validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  validates :text_or_image, presence: true
  mount_uploader :image, ImageUploader

  def created_time
    created_at.strftime('%Y年%m月%d日 %H時%M分')
  end

  private
  def text_or_image
    text.presence || image.presence
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :group_user
  has_many :messages
  has_many :groups, through: :group_user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new
    group = Group.create(group_params)
    if group.save
      redirect_to root_path, flash: {notice: "グループを作成しました。"}
    else
      flash[:alert] = "グループを作成できませんでした。"
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to root_path, flash: {notice: "グループを編集しました。"}
    else
      flash[:alert] = "グループを編集できませんでした。"
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, {user_ids: []})
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group, only: [:index, :create]
  before_action :set_message, only: [:index, :create]

  def index
    @message = Message.new
    respond_to do |format|
      format.html
      format.json do
        @messages = @group.messages.where('id > ?', params[:last_message_id])
      end
    end
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html{redirect_to group_messages_path(@group)}
        format.json
      end
    else
      flash[:alert] = "メッセージを入力してください。"
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:text, :image).merge(group_id: params[:group_id])
  end

  def set_group
    @groups = current_user.groups
    @group = Group.find(params[:group_id])
  end

  def set_message
    @messages = @group.messages
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def search
    name = params[:keyword]
    @users = User.where('name LIKE(?) and id != ?', "%#{name}%", current_user)
    respond_to do |format|
      format.json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label "グループ名", class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, placeholder: "グループ名を入力してください", class: "chat-group-form__input"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label 'チャットメンバーを追加', class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{ placeholder: '追加したいユーザー名を入力してください', type: 'text' }
      #user-search-result
    .chat-group-form__field--left
      = f.label "チャットメンバー", class: "chat-group-form__label"
    .chat-group-form__field--right
      #chat-group-users
        = current_user.name
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "Save", class: "chat-group-form__action-btn"

app/views/groups/_group.html.haml
= link_to group_messages_path(group) do
  %li.content-left__group--chat
    .content-left__group--chat--groupname
      = group.name
    .content-left__group--chat--groupmessage
      = group.messages.last.try(:text) || "まだメッセージはありません。"

app/views/groups/_groups.html.haml
= link_to group_messages_path(group.id) do
  %li.content-left__group--chat
    .content-left__group--chat--groupname
      = group.name
    .content-left__group--chat--groupmessage hellow,world

app/views/groups/_sidebar.html.haml
.content-left
  .content-left__user--name
    %h4
      = current_user.name
    = link_to edit_user_registration_path do
      %i.fa.fa-gear
    = link_to new_group_path do
      %i.fa.fa-pencil-square-o
  %ul.content-left__group
    %li.content-left__group--firstspace
      = render groups

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: "form"

app/views/groups/index.html.haml
!!!
%haml
  %head
  %body
    .content
      = render partial: "sidebar", locals: {groups: @groups}
      .content-right

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: "form"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    = csrf_meta_tags
  %body
    = render 'shared/header'
    = yield

app/views/messages/_message.html.haml
%li.content-right__chatsholder--chatspace--onechat{data: {message: {id: message.id}}}
  .username
    = message.user.name
  .chatdate
    = message.created_at
  .chattext
    = message.text
  = image_tag(message.image)

app/views/messages/index.html.haml
!!!
%haml
  %head
  %body
    .content
      = render partial: "groups/sidebar", locals: {groups: @groups}
      .content-right
        .content-right__group
          .content-right__group--groupzone
            .content-right__group--groupzone--name
              = @group.name
            .content-right__group--groupzone--member
              Members:
              - @group.users.each do |users|
                = users.name
          = link_to edit_group_path(@group) do
            .content-right__group--editbuttom Edit
        .content-right__chatsholder
          .content-right__chatsholder--firstspace
          %ul.content-right__chatsholder--chatspace
            = render @messages
        .content-right__bottom-bar
          = form_for [@group, @message] do |f|
            = f.text_field :text, placeholder: "type a message", class: "content-right__bottom-bar--textplace"
            = f.label :image do
              %i.fa.fa-image
            = f.file_field :image, style: "display: none;", class: "content-right__bottom-bar--photoplace"
            = f.submit "send", class: "content-right__bottom-bar--sendbuttom"

app/views/shared/_header.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash-#{key}")